unique_ids:
  forms:
    OrderForm: PGDQFD525NOK2ZGG4K6RI5QRJV67G6HK
    OrderForm.ItemTemplate1: UE6TOC2LNR2X3CULHLCDEPPAYSSBZCJV
    OrderForm.RowTemplate1: SEPURSD7J56XGXBFQYM7B75QORVZ3NNS
    Oven: '1715325002022220513642014.80585'
  modules: {}
  server_modules:
    EventzAnvilAPI: GB7MHALUS5MEEHTQW2YUVEIMKWZKF73W
    Pizza: PUQA5NEZXFYTAU6NLUE3FNFITVMCPJDY
    PizzaServerModule: CJL4MOJ2SEIUHBMMQPD23JNBCDJ6OTRC
    ServerModule1: 7UEFUJBOCKTYDVQQGPCB7DTHE7IVFMZB
  assets:
    standard-page.html: BI5LYEZ6CSA3J7BCYQFXO2SZ2PCFUCVI
    theme.css: 4Y4X4C4LJR7VQF57CU6LI2VFV66TKICD
  scripts: {}
