unique_ids:
  forms:
    Form1: PGDQFD525NOK2ZGG4K6RI5QRJV67G6HK
    Form1.ItemTemplate1: QKZGNP7UJA2T6X6S2TFYUFVJYSQPETQP
    Form1.RowTemplate1: SEPURSD7J56XGXBFQYM7B75QORVZ3NNS
  modules: {}
  server_modules:
    EventzAnvilAPI: WI3QOYX35SSRT5AALMLL6UP3NSMUCJ42
    ServerModule1: DK6J4QINQ2J5LQKU47A5GGAMFZLABLPP
  assets:
    standard-page.html: BI5LYEZ6CSA3J7BCYQFXO2SZ2PCFUCVI
    theme.css: 4Y4X4C4LJR7VQF57CU6LI2VFV66TKICD
  scripts: {}
